# The list of events the GitHub App subscribes to.
# Uncomment the event names below to enable them.
default_events:
  - issue_comment
  - issues
  - pull_request

# The set of permissions needed by the GitHub App. The format of the object uses
# the permission name for the key (for example, issues) and the access type for
# the value (for example, write).
# Valid values are `read`, `write`, and `none`
default_permissions:
  contents: write
  issues: write
  metadata: read
  pull_requests: write
